global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: airflow_webserver
    metrics_path: /health
    static_configs:
      - targets: ["airflow_webserver:8080"]

  - job_name: spark_master
    static_configs:
      - targets: ["spark_master:8080"]

  - job_name: spark_worker
    static_configs:
      - targets: ["spark_worker:8081"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: dbt_web_backend
    metrics_path: /metrics
    static_configs:
      - targets: ["dbt-web-backend:8010"]

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
