apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataops-dev
  namespace: argocd
spec:
  project: dataops-platform
  source:
    repoURL: https://github.com/example-org/dataops-showcase.git
    targetRevision: develop
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dataops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
