apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dataops-prod
  namespace: argocd
spec:
  project: dataops-platform
  source:
    repoURL: https://github.com/example-org/dataops-showcase.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: dataops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
