from __future__ import annotations

import os

import pytest

_GENERATOR_STACK_ENV_KEYS: tuple[str, ...] = (
    "GENERATOR_MODE",
    "GENERATOR_TICK_SECONDS",
    "GENERATOR_SEED",
    "GENERATOR_SEED_USERS",
    "GENERATOR_SEED_SELLERS",
    "GENERATOR_SEED_PRODUCTS",
    "GENERATOR_ORDERS_PER_TICK_MIN",
    "GENERATOR_ORDERS_PER_TICK_MAX",
    "GENERATOR_CLICKS_PER_TICK_MIN",
    "GENERATOR_CLICKS_PER_TICK_MAX",
    "GENERATOR_MINIO_BATCH_TICKS",
    "GENERATOR_ENABLE_OLTP",
    "GENERATOR_ENABLE_KAFKA",
    "GENERATOR_ENABLE_REDIS",
    "GENERATOR_ENABLE_MINIO",
    "GENERATOR_ENABLE_EXTENSIONS",
    "GENERATOR_SETTINGS_FILE",
    "GENERATOR_SETTINGS_JSON",
    "GENERATOR_CONFIG_DIR",
    "GENERATOR_USE_META_STORE",
    "GENERATOR_META_DSN",
    "GENERATOR_PROFILE",
    "OLTP_DSN",
    "KAFKA_BOOTSTRAP_SERVERS",
    "KAFKA_TOPIC_CLICKSTREAM",
    "KAFKA_TOPIC_ORDERS",
    "KAFKA_TOPIC_PAYMENTS",
    "KAFKA_TOPIC_SHIPMENTS",
    "KAFKA_TOPIC_MARKETING_EMAIL",
    "KAFKA_TOPIC_SEO_ORGANIC",
    "KAFKA_TOPIC_HR_TIME_TRACKING",
    "KAFKA_TOPIC_FEATURE_FLAG_EVAL",
    "REDIS_URL",
    "REDIS_CHANNEL_ORDERS",
    "REDIS_CHANNEL_PAYMENTS",
    "REDIS_CHANNEL_CLICKSTREAM",
    "REDIS_STREAM_ORDERS",
    "REDIS_KEY_WEB_VITALS_PREFIX",
    "MINIO_ENDPOINT",
    "MINIO_ACCESS_KEY",
    "MINIO_SECRET_KEY",
    "MINIO_BUCKET_RAW",
    "MINIO_PREFIX_PAYMENTS",
    "MINIO_PREFIX_RETURNS",
    "MINIO_PREFIX_CATALOG",
    "MINIO_PREFIX_MARKETING_PERF",
    "MINIO_PREFIX_SEO_RANKINGS",
    "MINIO_PREFIX_TELEMETRY_PERF",
    "MINIO_PREFIX_TELEMETRY_ERRORS",
    "MINIO_PREFIX_HR_PERF",
)


def clear_generator_config_env(monkeypatch: pytest.MonkeyPatch) -> None:
    for k in _GENERATOR_STACK_ENV_KEYS:
        monkeypatch.delenv(k, raising=False)
    for k in list(os.environ.keys()):
        if k.startswith("GENERATOR_IT_"):
            monkeypatch.delenv(k, raising=False)
