spark.master                     spark://spark-master:7077
spark.eventLog.enabled           true
spark.eventLog.dir               file:/tmp/spark-events
spark.sql.shuffle.partitions     8
spark.sql.adaptive.enabled       true
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.hadoop.fs.defaultFS        file:///
spark.master.ui.reverseProxy     true
spark.master.ui.reverseProxy.uriPrefix /spark-master/
spark.worker.ui.reverseProxy     true
spark.worker.ui.reverseProxy.uriPrefix /spark-worker/
