apiVersion: 1

datasources:
  - name: PostgreSQL DWH
    uid: PGDWH
    type: postgres
    access: proxy
    url: postgres_olap:5432
    database: techmart_dwh
    user: olap_user
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: olap_pass
