apiVersion: 1

datasources:
  - name: PostgreSQL Airflow Meta
    uid: PGAAF
    type: postgres
    access: proxy
    url: postgres_metadb:5432
    database: airflow
    user: meta_user
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: meta_pass
